"""Create contracts

Revision ID: 09c5bd068caf
Revises: 
Create Date: 2022-02-09 04:41:16.540674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c5bd068caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('compiler', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('verified_date', sa.Date(), nullable=False),
    sa.Column('abi', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_contracts_address'), 'contracts', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_address'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
