"""Create contracts

Revision ID: 2c3b2081b9de
Revises: 
Create Date: 2022-02-09 06:39:12.798582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c3b2081b9de"
down_revision = None
branch_labels = None
depends_on = None


class TSVector(sa.types.TypeDecorator):
    impl = sa.dialects.postgresql.TSVECTOR
    cache_ok = True


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("compiler", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("verified_date", sa.Date(), nullable=False),
        sa.Column("abi", sa.TEXT(), nullable=False),
        sa.Column(
            "network_id",
            sa.Enum("mainnet", "fantom", "arbitrum", name="networkid"),
            nullable=False,
        ),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column(
            "__ts_vector__",
            TSVector(),
            sa.Computed("to_tsvector('simple', abi)", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_index(
        "ix_contracts___ts_vector__",
        "contracts",
        ["__ts_vector__"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_contracts_address"), "contracts", ["address"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contracts_address"), table_name="contracts")
    op.drop_index(
        "ix_contracts___ts_vector__", table_name="contracts", postgresql_using="gin"
    )
    op.drop_table("contracts")
    # ### end Alembic commands ###
