"""Create contracts

Revision ID: 72ed3f54a6ca
Revises: 
Create Date: 2022-02-09 20:41:24.173029

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.types import TypeDecorator

Base = declarative_base()


class TSVector(TypeDecorator):
    impl = TSVECTOR
    cache_ok = True


# revision identifiers, used by Alembic.
revision = "72ed3f54a6ca"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("compiler", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("verified_date", sa.Date(), nullable=False),
        sa.Column("abi", sa.TEXT(), nullable=False),
        sa.Column("source_code", sa.TEXT(), nullable=False),
        sa.Column(
            "network_id",
            sa.Enum("mainnet", "fantom", "arbitrum", name="networkid"),
            nullable=False,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column(
            "__ts_vector__",
            TSVector(),
            sa.Computed("to_tsvector('simple', abi || source_code)", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_index(
        "ix_contracts___ts_vector__",
        "contracts",
        ["__ts_vector__"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_contracts_address"), "contracts", ["address"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contracts_address"), table_name="contracts")
    op.drop_index(
        "ix_contracts___ts_vector__", table_name="contracts", postgresql_using="gin"
    )
    op.drop_table("contracts")
    # ### end Alembic commands ###
